CREATE DATABASE api;
CREATE DATABASE scheduler;
CREATE DATABASE notificator;

GRANT ALL PRIVILEGES ON DATABASE api TO cipher;
GRANT ALL PRIVILEGES ON DATABASE scheduler TO cipher;
GRANT ALL PRIVILEGES ON DATABASE notificator TO cipher;
