[database]
username = "cipher"
password = "cipher"
host = "localhost"
port = 5432
database = "api"
use_ssl = false

[scheduler]
scheme = "http"
host = "[::1]"
port = 50052

[api]
scheme = "http"
host = "0.0.0.0"
port = 3000
