[workspace]
members = [
    "crates/api",
    "crates/interfaces",
    "crates/notificator",
    "crates/proto",
    "crates/rotator",
    "crates/scheduler",
]
resolver = "3"

[workspace.dependencies]
"anyhow" = "1"
"axum" = { version = "0.8" }
"chrono" = "0.4"
config = { version = "0.15", features = ["toml"] }
diesel = { version = "2", features = ["chrono", "postgres", "r2d2", "uuid"] }
"thiserror" = "2"
"tokio" = { version = "1", features = ["full"] }
"tonic" = { version = "0.14" }
"tonic-prost" = { version = "0.14" }
"serde" = { version = "1", features = ["derive"] }
"prost" = { version = "0.14" }
"uuid" = { version = "1", features = ["v4"] }
