services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: cipher
      POSTGRES_PASSWORD: cipher
      POSTGRES_DB: cipher
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cipher
      RABBITMQ_DEFAULT_PASS: cipher

volumes:
  db_data:
