[database]
username = "cipher"
password = "cipher"
host = "localhost"
port = 5432
database = "scheduler"
use_ssl = false

[grpc]
scheme = "http"
host = "[::1]"
port = 50052

[worker]
concurrency = 10
poll_interval = 1000

[rabbitmq]
host = "localhost"
port = 5672
username = "cipher"
password = "cipher"
