[package]
name = "notificator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
common = { path = "../common" }
futures = { workspace = true }
interfaces = { path = "../interfaces" }
lapin = { workspace = true }
proto = { path = "../proto" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tokio-stream = { workspace = true }
